CREATE TABLE "Categories"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(100) NOT NULL UNIQUE
);


CREATE TABLE "Manufacturers"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(100) NOT NULL UNIQUE
);


CREATE TABLE "Suppliers"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(100) NOT NULL UNIQUE
);


CREATE TABLE "Units"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(50) NOT NULL UNIQUE
);


CREATE TABLE "Roles"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(100) NOT NULL UNIQUE
);


CREATE TABLE "OrderStatuses"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(100) NOT NULL UNIQUE
);


CREATE TABLE "Users"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RoleId" integer NOT NULL,
    "Surname" varchar(100) NOT NULL,
    "Name" varchar(100) NOT NULL,
    "Patronymic" varchar(100) NOT NULL,
    "Login" varchar(100) NOT NULL UNIQUE,
    "Password" varchar(100) NOT NULL,

    CONSTRAINT "FK_Users_Role"
        FOREIGN KEY ("RoleId")
        REFERENCES "Roles" ("Id")
);


CREATE TABLE "PickupPoints"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PostalIndex" varchar(20) NOT NULL,
    "City" varchar(100) NOT NULL,
    "Street" varchar(100) NOT NULL,
    "BuildingNumber" varchar(20),

    CONSTRAINT "UQ_PickupPoints_Address"
        UNIQUE ("PostalIndex", "City", "Street", "BuildingNumber")
);


CREATE TABLE "Products"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SKU" varchar(50) NOT NULL UNIQUE,
    "Name" varchar(200) NOT NULL,
    "UnitOfMeasurementId" integer NOT NULL,
    "Price" numeric(12,2) NOT NULL,
    "SupplierId" integer NOT NULL,
    "ManufacturerId" integer NOT NULL,
    "ProductCategoryId" integer NOT NULL,
    "CurrentDiscount" numeric(5,2) NOT NULL,
    "StockQuantity" integer NOT NULL,
    "Description" text NOT NULL,
    "Photo" varchar(255),

    CONSTRAINT "CK_Products_Price"
        CHECK ("Price" >= 0),

    CONSTRAINT "CK_Products_CurrentDiscount"
        CHECK ("CurrentDiscount" >= 0 AND "CurrentDiscount" <= 100),

    CONSTRAINT "CK_Products_StockQuantity"
        CHECK ("StockQuantity" >= 0),

    CONSTRAINT "FK_Products_UnitOfMeasurement"
        FOREIGN KEY ("UnitOfMeasurementId")
        REFERENCES "Units" ("Id"),

    CONSTRAINT "FK_Products_Supplier"
        FOREIGN KEY ("SupplierId")
        REFERENCES "Suppliers" ("Id"),

    CONSTRAINT "FK_Products_Manufacturer"
        FOREIGN KEY ("ManufacturerId")
        REFERENCES "Manufacturers" ("Id"),

    CONSTRAINT "FK_Products_ProductCategory"
        FOREIGN KEY ("ProductCategoryId")
        REFERENCES "Categories" ("Id")
);


CREATE TABLE "Orders"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Date" date NOT NULL,
    "DeliveryDate" date NOT NULL,
    "PickupPointId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Code" integer NOT NULL,
    "OrderStatusId" integer NOT NULL,

    CONSTRAINT "FK_Orders_PickupPoint"
        FOREIGN KEY ("PickupPointId")
        REFERENCES "PickupPoints" ("Id"),

    CONSTRAINT "FK_Orders_User"
        FOREIGN KEY ("UserId")
        REFERENCES "Users" ("Id"),

    CONSTRAINT "FK_Orders_OrderStatus"
        FOREIGN KEY ("OrderStatusId")
        REFERENCES "OrderStatuses" ("Id")
);


CREATE TABLE "OrderProducts"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OrderId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "Quantity" integer NOT NULL,

    CONSTRAINT "CK_OrderProducts_Quantity"
        CHECK ("Quantity" > 0),

    CONSTRAINT "FK_OrderProducts_Order"
        FOREIGN KEY ("OrderId")
        REFERENCES "Orders" ("Id"),

    CONSTRAINT "FK_OrderProducts_Product"
        FOREIGN KEY ("ProductId")
        REFERENCES "Products" ("Id"),

    CONSTRAINT "UQ_OrderProducts_OrderProduct"
        UNIQUE ("OrderId", "ProductId")
);